---
name: Gtk-HandyCList
version: 0.031
author:
  - Simon Cozens
abstract: ~
license: perl
requires:
  Gnome: 0
  Test::More: 0
provides:
  Gtk::HandyCList:
    file: lib/Gtk/HandyCList.pm
    version: 0.031
generated_by: Module::Build version 0.2611
